### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by qqspm** [camigord/DynamicSpikeDetectorPlugin#1]
Hi,

I was trying to compile your program and the compiler cannot link to a few header files. In particular I am unable to locate ProcessorHeaders.h, SpikeLib.h, and EditorHeaders.h. If you could point me in the right direction that would be much appreciated.

**Comment by camigord** [comment]
Hi, sorry for the late reply. 

The provided code is just a plugin for the OpenEphys GUI, you need to download and compile the GUI and then compile the plugins. The files you are missing belong to the main packaege. 

You can find a tutorial about how to install and compile both the GUI and the plugins [here](https://open-ephys.atlassian.net/wiki/display/OEW/Windows).

**Comment by qqspm** [comment]
Hi, 
Thank you for your kind reply.
However, I was following the exact instruction in Openephys plugin GUI.
I copied the SpikeDetectorDynamic folder under the Plugins folder. Then build the GUI in visual studio 2013. However, there are all the plugins except the SpikeDetectorDynamic plugin after I opened the Plugins.sln. The file formats are so different to the other existing ones which contains the project files. So I am not sure what is the problem.
Could you help me out from it?
Thank you so much!
Qiang

![image](https://cloud.githubusercontent.com/assets/26908946/24822183/e256535c-1bb8-11e7-9f37-93f8b9e807bd.png)
![image](https://cloud.githubusercontent.com/assets/26908946/24822177/d4a37802-1bb8-11e7-9459-ca446e468dcf.png)
![image](https://cloud.githubusercontent.com/assets/26908946/24822151/a34805d4-1bb8-11e7-8bec-5afcf9056041.png)

**Comment by camigord** [comment]
What do you mean with "the file formats are so different"? 

Why don't you try to follow [this](https://open-ephys.atlassian.net/wiki/display/OEW/Plugin+build+files) procedure to create a plugin, and then just copy/replace the files with the ones provided here.

I will try to compile the code again tonight and check if everything works properly.

**Comment by camigord** [comment]
Hi, I think I know what is your problem. You can check [here](https://open-ephys.atlassian.net/wiki/display/OEW/Tutorial%3A+Add+a+custom+processor) for a more detailed description about how to create a new processor plugin.

The basic idea is that the files I provided in this repo are supposed to be located under _Source/Plugins_ (This would be the location of the source code). The VisualStudio project which you need to create and compile needs to be located under  _Builds/VisualStudio2013/Plugins_. You need to add a reference to the previous files in this project and then compile it.

I think that if you follow the instructions everything should work properly.

Regards,

**Comment by qqspm** [comment]
I will try them. Will let you know. 
Thank you very much for the help.
